# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20170824_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
